support for running all the test cases
localstack/localstack-terraform-test pull request #14
Opened 2023-01-13 16:07 UTC by macnev2013

## Motivation
We are using terraform test suite as a quality gate for each PR, but flakiness of the suite is causing a lot of frictions for the dev team.

For us, the parity metrics of the terraform test suite provides more value than using it as a quality gate. So we have decided to externalise the test suite and schedule it to run at a certain time interval.

## Features
- Python CLI tool:
  - Patches the terraform repository
  - Builds testing binaries for localstack community/pro/all supported services based on parameters
- Pytest plugin to list and execute test cases written in golang
- Pytest hook that launches LocalStack with a certain Docker image depending on the argument
- Github actions
  - Executes all test for all services in concurrent runner
  - Publishes test results in workflow's summary
  - Scheduled test execution (once a week)

2023-01-16 14:20 UTC, thrau requested changes
overall those are very cool changes!

my two biggest points are:
1. it doesn't work on my local machine. probably missing some docs on how to build the binary.
2. code and project organization could be improved by making it consistent with our other python projects (concrete comments inline) 


## Functionality

i tested the readme and the collection works

```
 % python -m pytest --co | head
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/thomas/workspace/localstack/localstack-terraform-test
collected 7448 items

<GoFile terraform-provider-aws/internal/acctest/provider_test.go>
  <GoItem TestAccProvider_DefaultTags_emptyBlock>
  <GoItem TestAccProvider_DefaultTagsTags_none>
  <GoItem TestAccProvider_DefaultTagsTags_one>
  <GoItem TestAccProvider_DefaultTagsTags_multiple>
```


when running tests, however, i get some errors:

```
thomas@om ~/workspace/localstack/localstack-terraform-test
 % python -m pytest terraform-provider-aws/internal/service/sqs           
============================================================================================================= test session starts =============================================================================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/thomas/workspace/localstack/localstack-terraform-test
collected 35 items                                                                                                                                                                                                                            

terraform-provider-aws/internal/service/sqs/queue_data_source_test.go FF                                                                                                                                                                [  5%]
terraform-provider-aws/internal/service/sqs/queue_policy_test.go FFFF                                                                                                                                                                   [ 17%]
terraform-provider-aws/internal/service/sqs/queue_redrive_allow_policy_test.go FFFF                                                                                                                                                     [ 28%]
terraform-provider-aws/internal/service/sqs/queue_redrive_policy_test.go FFFF                                                                                                                                                           [ 40%]
terraform-provider-aws/internal/service/sqs/queue_test.go FFFFFFFFFFFFFFFFFFFFF                                                                                                                                                         [100%]

================================================================================================================== FAILURES ===================================================================================================================
_________________________________________________________________________________________________ Test Case: TestAccSQSQueueDataSource_basic __________________________________________________________________________________________________
Failure Reason:
sh: 1: ./test-bin/sqs.test: not found

__________________________________________________________________________________________________ Test Case: TestAccSQSQueueDataSource_tags __________________________________________________________________________________________________
Failure Reason:
sh: 1: ./test-bin/sqs.test: not found

___________________________________________________________________________________________________ Test Case: TestAccSQSQueuePolicy_basic ____________________________________________________________________________________________________
Failure Reason:
sh: 1: ./test-bin/sqs.test: not found
```

i assume this is because i need the test binary, but i don't know how to build it using the instructions given to me.

2023-01-16 14:20 UTC, thrau commented on README.md
> +3. Run `source venv/bin/activate` to activate the virtual environment
nit: our typical pattern is the hidden folder `.venv`, maybe we could keep that consistent with other projects

2023-01-16 14:20 UTC, thrau commented on conftest.py
> +import pytest
since this is a pytest file for running tests, it should probably move into `tests/`

2023-01-16 14:20 UTC, thrau commented on main.py
> +from timeit import default_timer as timer
maybe we could move all python files into their own module. i know this is not a traditional python distribution, but i think having a module like `terraform_pytest` or something, that holds all of the python files would be useful.

you can then call main by `python -m terraform_pytest.main`

2023-01-16 14:20 UTC, thrau commented on main.py
> +    pass
noticing that we are not using the black codestyle here. maybe we can include a makefile and the project config with black and isort like have in our basic cookiecutter https://github.com/localstack/cookiecutter/tree/main/python-application/%7B%7Bcookiecutter.project_slug%7D%7D

2023-01-17 06:03 UTC, macnev2013 commented on README.md
> +3. Run `source venv/bin/activate` to activate the virtual environment
Hey Thomas, thanks for trying out. Updated the readme.

2023-01-17 06:05 UTC, macnev2013 commented on conftest.py
> +import pytest
In this case, we wont be able to move conftest in `tests/` - as our tests are located in `rootfolder/terraform-provider-aws` due to which conftest file wont be picked up.

2023-01-17 06:06 UTC, macnev2013 commented on main.py
> +from timeit import default_timer as timer
Agreed. Moved related files.

2023-01-17 06:07 UTC, macnev2013 commented on main.py
> +    pass
Thanks for the reference. I've added it in to the project.

2023-01-19 09:23 UTC, macnev2013 commented
Hey @thrau , 

> 1. it doesn't work on my local machine. probably missing some docs on how to build the binary.

Sorry missed to add this in the readme earlier. 
- You need to run `python -m terraform_pytest.main build -s all` to build the testing binary or you can build the binary for specific service by `python -m terraform_pytest.main build -s s3` before running the test cases with pytest.

Let me know how it goes.

2023-01-19 13:33 UTC, thrau reviewed
hey! just testing the open PR. i can't seem to build the go test binary. any idea what's going on? i feel this part of the pipeline should be fairly reliable.

after adding some more log output (unfortunately the line 156 in utils.py swallows all the output), i got this:
```
thomas@om ~/workspace/localstack/localstack-terraform-test
 % python -m terraform_pytest.main build -s s3
Building s3...
Traceback (most recent call last):
  File "/home/thomas/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/thomas/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/main.py", line 56, in <module>
    cli()
  File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/main.py", line 42, in build
    build_test_bin(service=service, tf_root_path=realpath(TF_REPO_NAME))
  File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/utils.py", line 156, in build_test_bin
    raise Exception(f"Error while building test binary for {service}: {stdout}")
Exception: Error while building test binary for s3: go: github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.18 requires
	github.com/aws/aws-sdk-go@v1.42.52: missing go.sum entry; to add it:
	go mod download github.com/aws/aws-sdk-go
```

after going into the terraform provider submodule and running `go mod download github.com/aws/aws-sdk-go`
it seems to work.

but maybe it would be good to be sure that the command runs without errors on a user's machine?

you can also tell me that you think this is unimportant since this will always run in CI. happy to argue :smile:

2023-01-20 10:25 UTC, alexrashed requested changes
This is really an awesome set of changes. I was a bit nitpicky with the review, but a lot of the comments are just comments for the next iteration of the project.
I'm really looking forward to having the tests and their parity data being run and collected automatically. 🚀

2023-01-20 10:25 UTC, alexrashed commented on conftest.py
> +import os
nit: This is where the magic happens, but to be honest, without deeper knowledge on the pytest plugin mechanism I don't really know what's happening here. Please add some useful comments to describe what the different classes and functions do.

2023-01-20 10:25 UTC, alexrashed commented on conftest.py
> +    env_vars = ["DEBUG=1", "PROVIDER_OVERRIDE_S3=asf", "FAIL_FAST=1"]
nit: This function (as well as stop, health check, service health) are nicely implemented in the localstack CLI. In a next iteration we might be able to just use the CLI here? It can just start localstack with the correct ports and environment variables, can request the health endpoint, can wait for an instance to be up and running, and can stop a running instance.

2023-01-20 10:25 UTC, alexrashed commented on terraform_pytest/main.py
> +        return
This should be done by click. Just add a `required=True` to the option decorator.

2023-01-20 10:25 UTC, alexrashed commented on terraform_pytest/main.py
> +    services = get_services(service)
nit: I think it would be nice if there would be some kind of feedback if I add a service which is not supported (maybe a typo?). If I add only a single service and this one does not exist, it will just not do anything, right?

2023-01-20 10:25 UTC, alexrashed commented on .github/workflows/main.yml
> +        python -m pytest --junitxml=target/reports/pytest.xml terraform-provider-aws/internal/service/${{ matrix.service }} -s -v -n 2
I think the separation of parallel and non-parallel executions of the service tests isn't really necessary.
Something like this might work for both cases:
```
    - name: Run ${{ matrix.service }} Tests
      env:
        PYTEST_PARALLEL_CONFIG: "${{ matrix.service == 'ec2' && '-n 2' || '' }}"
      run: |
        python -m pytest $PYTEST_PARALLEL_CONFIG --junitxml=target/reports/pytest.xml terraform-provider-aws/internal/service/${{ matrix.service }} -s -v --ls-start --ls-image ${{ github.event.inputs.localstack-image || 'localstack/localstack:latest' }}
```

2023-01-20 10:58 UTC, macnev2013 commented on docker-compose.yml
> +version: "3.8"
We are using `pytest_configure` and `pytest_unconfigure` method to start and stop the localstack instance.
- python_configure is called for every plugin and initial conftest file after command line options have been parsed
- python_unconfigure is called before test process is exited.

- When we run test cases in parallel (in case of ec2) - pytest tries to start two instance of Localstack. Which is raising the exception.
- I've tried other hooks as well such as - `pytest_sessionstart` and `pytest_sessionfinish`. But it's behaving the same.

- So when we run the tests in parallel - we need to use a separate localstack instance.

2023-01-20 10:59 UTC, macnev2013 commented on terraform_pytest/utils.py
> +LS_COMMUNITY_SERVICES = [
Sounds good. I'll take a note of it.

2023-01-20 11:10 UTC, macnev2013 commented on terraform_pytest/utils.py
> +    if exists(_test_bin_abs_path):
I'm not sure how we can determine submodule updation..

I've added `--force-build` flag in the cli to build the binary even if it exists.

2023-01-20 11:11 UTC, macnev2013 commented on terraform_pytest/utils.py
> +import signal
Noted.

2023-01-20 11:16 UTC, macnev2013 commented on terraform_pytest/utils.py
> +import signal
Yes. Can be done with make target or shell script as well. But it might get a bit complex if we add multiple configurations options.

2023-01-20 11:18 UTC, alexrashed commented on terraform_pytest/utils.py
> +import signal
Yeah, that's true, the complexity of makefiles when not being use for compile tasks can grow quite fast. :)

2023-01-20 11:19 UTC, macnev2013 commented on conftest.py
> +    env_vars = ["DEBUG=1", "PROVIDER_OVERRIDE_S3=asf", "FAIL_FAST=1"]
Sounds great. Let's try to use the CLI in next iteration.

2023-01-20 11:19 UTC, alexrashed commented on terraform_pytest/utils.py
> +    if exists(_test_bin_abs_path):
Yeah, a force-build would do the trick as well. I just want to avoid that you have to have a deeper knowledge about the build process to be able to re-trigger it (because you would have to know that there is some kind of binary target folder which you need to remove to trigger a rebuild). So a force-build is fine for me :)

2023-01-20 11:20 UTC, alexrashed commented on terraform_pytest/utils.py
> +BLACKLISTED_SERVICES = ["controltower", "greengrass"]
Ah, okay, then please add a comment describing just that.

2023-01-20 11:20 UTC, macnev2013 commented on terraform_pytest/main.py
> +        return
Nice one. thanks :)

2023-01-20 11:32 UTC, alexrashed commented on docker-compose.yml
> +version: "3.8"
To be honest, this seems a bit hacky. Running a fixture / setup code only once when using xdist actually really doesn't seem to be straight forward. But there are some workarounds, f.e. by checking the config if you are the main process:
https://github.com/pytest-dev/pytest-xdist/issues/271#issuecomment-826396320
This way you could basically implement a trivial "leader election": The main process is the lead, it is responsible of starting localstack. All processes (including the lead) afterwards just wait for localstack to be up and running.

2023-01-20 13:27 UTC, macnev2013 commented
> hey! just testing the open PR. i can't seem to build the go test binary. any idea what's going on? i feel this part of the pipeline should be fairly reliable.
> 
> after adding some more log output (unfortunately the line 156 in utils.py swallows all the output), i got this:
> 
> ```
> thomas@om ~/workspace/localstack/localstack-terraform-test
>  % python -m terraform_pytest.main build -s s3
> Building s3...
> Traceback (most recent call last):
>   File "/home/thomas/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/thomas/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/main.py", line 56, in <module>
>     cli()
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/main.py", line 42, in build
>     build_test_bin(service=service, tf_root_path=realpath(TF_REPO_NAME))
>   File "/home/thomas/workspace/localstack/localstack-terraform-test/terraform_pytest/utils.py", line 156, in build_test_bin
>     raise Exception(f"Error while building test binary for {service}: {stdout}")
> Exception: Error while building test binary for s3: go: github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.18 requires
> 	github.com/aws/aws-sdk-go@v1.42.52: missing go.sum entry; to add it:
> 	go mod download github.com/aws/aws-sdk-go
> ```
> 
> after going into the terraform provider submodule and running `go mod download github.com/aws/aws-sdk-go` it seems to work.
> 
> but maybe it would be good to be sure that the command runs without errors on a user's machine?
> 
> you can also tell me that you think this is unimportant since this will always run in CI. happy to argue 😄

@thrau I've tried to reproduce the issue in my system as well as some other systems. Seems like its working fine for me. Still I'm adding a blind fix which should take care of it.

2023-01-20 13:29 UTC, macnev2013 commented on .github/workflows/main.yml
> +#      - pytest-plugin
deleted.

2023-01-23 08:28 UTC, macnev2013 commented on pyproject.toml
> +include = '(^terraform_pytest\/.*\.py$|^conftest.py$)'
Updated.

2023-01-23 08:28 UTC, macnev2013 commented on pyproject.toml
> +#extend_skip = []
removed

2023-01-23 08:30 UTC, macnev2013 commented on pyproject.toml
> +filterwarnings =["ignore::DeprecationWarning"]
Fixed those warning and removed `deprecation warnings` from here.

2023-01-23 08:33 UTC, macnev2013 commented on Makefile
> +format:
Added both - pre-commit and pipeline.

2023-01-23 08:34 UTC, macnev2013 commented on docker-compose.yml
> +version: "3.8"
Used the approach described https://github.com/pytest-dev/pytest-xdist/issues/271#issuecomment-826396320. Also, deleted docker-compose file.

2023-01-23 08:35 UTC, macnev2013 commented on terraform_pytest/utils.py
> +    return f"{TF_REPO_PATH}/{TF_TEST_BINARY_FOLDER}/{service}.test"
Removed.

2023-01-23 08:35 UTC, macnev2013 commented on terraform_pytest/utils.py
> +def get_services(service):
Add docs across the project.

2023-01-23 08:36 UTC, macnev2013 commented on conftest.py
> +import os
Added short description in the functions about the usage..

2023-01-23 08:55 UTC, macnev2013 commented on .github/workflows/main.yml
> +        python -m pytest --junitxml=target/reports/pytest.xml terraform-provider-aws/internal/service/${{ matrix.service }} -s -v -n 2
Updated the pipeline.

2023-01-23 09:30 UTC, macnev2013 commented on terraform_pytest/utils.py
> +BLACKLISTED_SERVICES = ["controltower", "greengrass"]
Added comments.

2023-01-23 09:33 UTC, macnev2013 commented on .gitmodules
>  	url = https://github.com/hashicorp/terraform-provider-aws.git
Terraform test cases are not updated regularly. We can pin the version and update it once every month manually. That would be a better approach as we will have the confidence that the tests won't fail without us knowing it.

2023-01-23 11:00 UTC, alexrashed commented on .gitmodules
>  	url = https://github.com/hashicorp/terraform-provider-aws.git
There's definitely a lot of activity in the repo: https://github.com/hashicorp/terraform-provider-aws/pulse
Why would you say that the test cases aren't updated regularly?
But nevertheless, I think the best approach would be (in the next iteration) to pin a specific version of the repo (i.e. a tag) and use an automation to update them automatically (f.e. with renovate bot or dependabot - which both have at least rudimentary support for git submodules).

2023-01-23 11:14 UTC, alexrashed approved these changes
Thanks for addressing all the PR comments!
I only added two small comments (small nitpicks): A small enhancement to the README and the deletion of the compose file.
From my perspective, we're good to go with the first iteration! 🚀 
I tested it locally on my machine with STS (which worked fine). @thrau maybe we could address your issues with the next iteration?

2023-01-23 11:25 UTC, macnev2013 commented on README.md
> +1. Run `python -m terraform_pytest.main patch` to apply the patch to the terraform provider aws
added a note in readme

2023-01-23 11:31 UTC, macnev2013 commented on .gitmodules
>  	url = https://github.com/hashicorp/terraform-provider-aws.git
Specific test files (_test.go) are not updated too frequently such as [this](https://github.com/hashicorp/terraform-provider-aws/commits/main/internal/service/s3/bucket_acl_test.go).

But yes, overall activity is high. Let's plan this for next iteration.

2023-01-23 15:19 UTC, merged